---
services:
  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - postgresql
      - chirpstack-network-server
      - emqx

  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - emqx

  redis:
    image: redis:6-alpine
    command: redis-server --save "" --appendonly no

  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=root
    command: postgres -c max_connections=1024
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  emqx:
    image: nats
    command: -c /etc/nats/nats-server.conf
    volumes:
      - ./configuration/nats-server.conf:/etc/nats/nats-server.conf
    ports:
      - 1883:1883
      - 4222:4222
      - 8222:8222

volumes:
  postgresqldata:
