---

services:
  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - postgresql
      - chirpstack-network-server
      - emqx

  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - emqx

  redis:
    image: redis:6-alpine
    command: redis-server --save "" --appendonly no

  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=root
    command: postgres -c max_connections=1024
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  emqx:
    image: emqx/emqx:4.4.0
    environment:
      EMQX_ZONE__EXTERNAL__MAX_INFLIGHT: 1024000
      EMQX_ZONE__EXTERNAL__FORCE_GC_POLICY: 5000000000|5000MB
      EMQX_LISTENER__TCP__EXTERNAL__SEND_TIMEOUT: 2h
      EMQX_LISTENER__TCP__EXTERNAL__ACCEPTORS: 100
      EMQX_LISTENER__TCP__EXTERNAL__ACTIVE_N: 1024
    ports:
      - 1883:1883
      - 18083:18083

volumes:
  postgresqldata:
