---

services:
  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - postgresql
      - chirpstack-network-server
      - emqx

  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - emqx

  redis:
    image: redis:6-alpine

  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  emqx:
    image: emqx/emqx:4.3.11
    ports:
      - 1883:1883
      - 18083:18083

volumes:
  postgresqldata:
